import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TopNav from '@/components/TopNav';
import { cookies } from 'next/headers';
import VovkTextLogo from '@/components/VovkTextLogo';
import HomeLink from '@/components/HomeLink';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, ...xxx }: { children: React.ReactNode }) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme') ?? { value: 'light' };
  const isDarkMode = theme.value === 'dark';

  return (
    <html lang="en" className={isDarkMode ? 'dark' : undefined}>
      <body className={`${inter.className} bg-[#0d1117f7] text-white`}>
        <header className="flex items-center justify-between px-6 py-3">
          <div className="flex items-center gap-2">
            <div className="flex flex-col">
              <a href="https://vovk.dev" className="text-black dark:text-white ">
                <VovkTextLogo width={150} />
              </a>
              <div>
                <HomeLink />
              </div>
            </div>
          </div>
          <TopNav defaultIsDarkMode={isDarkMode} />
        </header>
        <div className="p-6 ">{children}</div>
      </body>
    </html>
  );
}
