// Generated by vovk-cli v0.0.1-draft.387 at 2025-11-01T15:14:11.724Z

import segment0 from './../../.vovk-schema/root.json' with { type: 'json' };

import segment1 from './../../.vovk-schema/static.json' with { type: 'json' };

import meta from './../../.vovk-schema/_meta.json' with { type: 'json' };

const segments = {
  '': segment0,
  static: segment1,
};

export const schema = {
  $schema: 'https://vovk.dev/api/schema/v3/schema.json',
  segments,
  meta,
};
